[2025-09-18T16:05:32.167+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T16:05:32.209+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_branch_demo.branch_on_env manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:05:32.219+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_branch_demo.branch_on_env manual__2025-09-18T15:50:51.823082+00:00 [queued]>
[2025-09-18T16:05:32.220+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T16:05:32.237+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_on_env> on 2025-09-18 15:50:51.823082+00:00
[2025-09-18T16:05:32.245+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=564) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-18T16:05:32.244+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sensor_branch_demo', 'branch_on_env', 'manual__2025-09-18T15:50:51.823082+00:00', '--job-id', '306', '--raw', '--subdir', 'DAGS_FOLDER/sensor_branch.py', '--cfg-path', '/tmp/tmp21yc75ak']
[2025-09-18T16:05:32.246+0000] {standard_task_runner.py:64} INFO - Started process 565 to run task
[2025-09-18T16:05:32.247+0000] {standard_task_runner.py:91} INFO - Job 306: Subtask branch_on_env
[2025-09-18T16:05:32.322+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_branch_demo.branch_on_env manual__2025-09-18T15:50:51.823082+00:00 [running]> on host 05510bc62330
[2025-09-18T16:05:32.424+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sensor_branch_demo' AIRFLOW_CTX_TASK_ID='branch_on_env' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T15:50:51.823082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T15:50:51.823082+00:00'
[2025-09-18T16:05:32.426+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T16:05:32.426+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-09-18T16:05:32.442+0000] {python.py:237} INFO - Done. Returned value was: process
[2025-09-18T16:05:32.442+0000] {branch.py:36} INFO - Branch into process
[2025-09-18T16:05:32.443+0000] {skipmixin.py:178} INFO - Following branch process
[2025-09-18T16:05:32.468+0000] {skipmixin.py:246} INFO - Skipping tasks [('skip', -1)]
[2025-09-18T16:05:32.509+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T16:05:32.544+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sensor_branch_demo, task_id=branch_on_env, run_id=manual__2025-09-18T15:50:51.823082+00:00, execution_date=20250918T155051, start_date=20250918T160532, end_date=20250918T160532
[2025-09-18T16:05:32.583+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-18T16:05:32.610+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T16:05:32.619+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
